name: "build"
description: "Build ROOT file"
author: "josh@joshchen.io"

inputs:
  TOOL_ARGS:
    description: "Tool and argument invokation"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

