name: "Isabelle action"
description: "Run Isabelle"
author: "josh@joshchen.io"

inputs:
  TOOL_ARGS:
    description: "Isabelle tool to invoke and arguments to pass"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

